// dashboard/src/plugins/nut/users/ChangePassword.vue
<template>
  <dashboard-layout v-bind:title="title">
    <v-flex md6>
      <v-card>
        <v-card-title primary-title>
          <h3 class="headline mb-0">{{title}}</h3>
        </v-card-title>
        <v-form>
          <v-text-field
            prepend-icon="lock"
            name="currentPassword"
            :error-messages="errors.collect('currentPassword')"
            v-model="currentPassword"
            v-validate="'required'"
            :label="this.$t('form.labels.current-password')"
            type="password"
          />
          <v-text-field
            id="newPassword"
            prepend-icon="lock"
            :error-messages="errors.collect('newPassword')"
            v-model="newPassword"
            ref="newPassword"
            name="newPassword"
            v-validate="'required|min:6|max:32'"
            :label="this.$t('form.labels.new-password')"
            type="password"
          />
          <v-text-field
            id="passwordConfirmation"
            :error-messages="errors.collect('passwordConfirmation')"
            prepend-icon="lock"
            v-validate="'required|confirmed:newPassword'"
            v-model="passwordConfirmation"
            name="passwordConfirmation"
            :label="this.$t('form.labels.password-confirmation')"
            type="password"
          />
        </v-form>
        <v-card-actions>
          <v-spacer/>
          <v-btn v-on:click="submit" color="primary">{{$t('buttons.submit')}}</v-btn>
        </v-card-actions>
      </v-card>
    </v-flex>
    <notification-bar :alert="alert"/>
  </dashboard-layout>
</template>

<script>
import { post as httpPost } from "@/request";

export default {
  name: "users-change-password",
  computed: {
    title() {
      return this.$i18n.t("nut.users.change-password.title");
    }
  },
  data() {
    return {
      currentPassword: null,
      newPassword: null,
      passwordConfirmation: null,
      alert: {}
    };
  },
  methods: {
    async submit(e) {
      e.preventDefault();
      this.alert = {};
      const isValid = await this.$validator.validate();
      if (isValid) {
        httpPost("/users/change-password", {
          currentPassword: this.currentPassword,
          newPassword: this.newPassword
        })
          .then(() => {
            this.alert = { ok: true, message: this.$i18n.t("flashes.success") };
          })
          .catch(err => {
            this.alert = { ok: false, message: err };
          });
      }
    }
  }
};
</script>

// dashboard/src/pages/users/ChangePassword.tsx
import { Form, Input, message } from 'antd'
import { FormComponentProps } from 'antd/lib/form/Form'
import * as React from 'react'
import { FormattedMessage, InjectedIntlProps, injectIntl, intlShape } from 'react-intl'

import { Authorized } from '../../components/authorized'
import { formItemLayout } from '../../components/form'
import Layout from '../../components/form/Layout'
import Submit from '../../components/form/Submit'
import { httpPost } from '../../utils/request'

const FormItem = Form.Item

class Widget extends React.Component<InjectedIntlProps & FormComponentProps> {
  public static propTypes: React.ValidationMap<any> = {
    intl: intlShape.isRequired,
  }
  public comparePasswords = (_: any, value: string, callback: (m?: string) => void) => {
    const { form, intl } = this.props
    if (value && value !== form.getFieldValue('newPassword')) {
      callback(intl.formatMessage({ id: "form.validations.password-confirmation" }))
    } else {
      callback()
    }
  }
  public handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const { form, intl } = this.props
    form.validateFields((err, values) => {
      if (!err) {
        httpPost("/users/change-password", values).then((_) => {
          message.success(intl.formatMessage({ id: "flashes.success" }))
          form.setFieldsValue({ currentPassword: '', newPassword: '', passwordConfirmation: '' })
        }).catch(message.error)
      }
    })
  }
  public render() {
    const { formatMessage } = this.props.intl
    const { getFieldDecorator } = this.props.form

    return (<Authorized>
      <Layout title={{ id: "nut.users.change-password.title" }}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.current-password" />}>
            {
              getFieldDecorator('currentPassword', {
                rules: [
                  {
                    message: formatMessage({ id: "form.validations.required" }),
                    required: true,
                  }
                ]
              })(<Input type="password" />)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.new-password" />}>
            {
              getFieldDecorator('newPassword', {
                rules: [
                  {
                    max: 32,
                    message: formatMessage({ id: "form.validations.password" }),
                    min: 6,
                    required: true,
                  }
                ]
              })(<Input type="password" />)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.password-confirmation" />}>
            {
              getFieldDecorator('passwordConfirmation', {
                rules: [
                  {
                    message: formatMessage({ id: "form.validations.required" }),
                    required: true,
                  },
                  {
                    validator: this.comparePasswords,
                  },
                ]
              })(<Input type="password" />)
            }
          </FormItem>
          <Submit />
        </Form>
      </Layout>
    </Authorized>)
  }
}


export default injectIntl(Form.create()(Widget))
