// dashboard/src/plugins/nut/users/Profile.vue
<template>
  <dashboard-layout v-bind:title="title">
    <v-flex md6>
      <v-card>
        <v-card-title primary-title>
          <h3 class="headline mb-0">{{title}}</h3>
        </v-card-title>
        <v-form>
          <v-text-field
            prepend-icon="perm_identity"
            name="nickName"
            v-model="nickName"
            disabled
            :label="this.$t('form.labels.nickname')"
            type="text"
          />
          <v-text-field
            prepend-icon="email"
            name="email"
            v-model="email"
            disabled
            :label="this.$t('form.labels.email')"
            type="email"
          />
          <v-text-field
            prepend-icon="person_pin"
            name="realName"
            :error-messages="errors.collect('realName')"
            v-model="realName"
            v-validate="'required'"
            :label="this.$t('form.labels.real-name')"
            type="text"
          />
          <v-text-field
            prepend-icon="credit_card"
            name="logo"
            :error-messages="errors.collect('logo')"
            v-model="logo"
            v-validate="'required'"
            :label="this.$t('form.labels.logo')"
            type="text"
          />
        </v-form>
        <v-card-actions>
          <v-spacer/>
          <v-btn v-on:click="submit" color="primary">{{$t('buttons.submit')}}</v-btn>
        </v-card-actions>
      </v-card>
    </v-flex>
    <notification-bar :alert="alert"/>
  </dashboard-layout>
</template>

<script>
import { get as httpGet, post as httpPost } from "@/request";

export default {
  name: "users-profile",
  computed: {
    title() {
      return this.$i18n.t("nut.users.profile.title");
    }
  },
  data() {
    return {
      email: null,
      nickName: null,
      realName: null,
      logo: null,
      alert: {}
    };
  },
  created() {
    httpGet("/users/profile").then(rst => {
      this.email = rst.email;
      this.realName = rst.realName;
      this.logo = rst.logo;
      this.nickName = rst.nickName;
    });
  },
  methods: {
    async submit(e) {
      e.preventDefault();
      this.alert = {};
      const isValid = await this.$validator.validate();
      if (isValid) {
        httpPost("/users/profile", {
          logo: this.logo,
          realName: this.realName
        })
          .then(() => {
            this.alert = { ok: true, message: this.$i18n.t("flashes.success") };
          })
          .catch(err => {
            this.alert = { ok: false, message: err };
          });
      }
    }
  }
};
</script>

// dashboard/src/pages/users/Profile.tsx
import { Form, Input, message } from 'antd'
import { FormComponentProps } from 'antd/lib/form/Form'
import * as React from 'react'
import { FormattedMessage, InjectedIntlProps, injectIntl, intlShape } from 'react-intl'

import { Authorized } from '../../components/authorized'
import { formItemLayout } from '../../components/form'
import Layout from '../../components/form/Layout'
import Submit from '../../components/form/Submit'
import { httpGet, httpPost } from '../../utils/request'

const FormItem = Form.Item

class Widget extends React.Component<InjectedIntlProps & FormComponentProps> {
  public static propTypes: React.ValidationMap<any> = {
    intl: intlShape.isRequired,
  }
  public componentDidMount() {
    const { form } = this.props
    httpGet(`/users/profile`).then((rst) => {
      form.setFieldsValue(rst)
    }).catch(message.error)
  }
  public handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const { form, intl } = this.props
    form.validateFields((err, values) => {
      if (!err) {
        httpPost("/users/profile", values).then((_) => {
          message.success(intl.formatMessage({ id: "flashes.success" }))
        }).catch(message.error)
      }
    })
  }
  public render() {
    const { formatMessage } = this.props.intl
    const { getFieldDecorator } = this.props.form

    return (<Authorized>
      <Layout title={{ id: "nut.users.profile.title" }}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.nick-name" />}>
            {
              getFieldDecorator('nickName', {
                rules: [
                  {
                    required: true,
                  }
                ]
              })(<Input disabled={true} />)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.email" />}>
            {
              getFieldDecorator('email', {
                rules: [
                  {
                    required: true,
                  }
                ]
              })(<Input disabled={true} type="email" />)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.real-name" />}>
            {
              getFieldDecorator('realName', {
                rules: [
                  {
                    max: 32,
                    message: formatMessage({ id: "form.validations.username" }),
                    min: 2,
                    required: true,
                  }
                ]
              })(<Input />)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.logo" />}>
            {
              getFieldDecorator('logo', {
                rules: [
                  {
                    message: formatMessage({ id: "form.validations.required" }),
                    required: true,
                  }
                ]
              })(<Input />)
            }
          </FormItem>

          <Submit />
        </Form>
      </Layout>
    </Authorized>)
  }
}


export default injectIntl(Form.create()(Widget))
