// dashboard/src/plugins/nut/Install.vue
<template>
  <application-layout
    v-bind:alert="alert"
    v-bind:onSubmit="submit"
    v-bind:title="this.$t('nut.install.title')"
  >
    <v-form>
      <v-text-field
        prepend-icon="person"
        name="realName"
        v-model="realName"
        :error-messages="errors.collect('realName')"
        v-validate="'required'"
        :label="this.$t('form.labels.real-name')"
        type="text"
      />
      <v-text-field
        prepend-icon="email"
        name="email"
        :error-messages="errors.collect('email')"
        v-model="email"
        v-validate="'required|email'"
        :label="this.$t('form.labels.email')"
        type="email"
      />
      <v-text-field
        id="password"
        prepend-icon="lock"
        :error-messages="errors.collect('password')"
        v-model="password"
        ref="password"
        name="password"
        v-validate="'required|min:6|max:32'"
        :label="this.$t('form.labels.password')"
        type="password"
      />
      <v-text-field
        id="passwordConfirmation"
        :error-messages="errors.collect('passwordConfirmation')"
        prepend-icon="lock"
        v-validate="'required|confirmed:password'"
        v-model="passwordConfirmation"
        name="passwordConfirmation"
        :label="this.$t('form.labels.password-confirmation')"
        type="password"
      />
    </v-form>
  </application-layout>
</template>

<script>
import { post as httpPost } from "@/request";

export default {
  name: "install",
  data() {
    return {
      email: null,
      realName: null,
      password: null,
      passwordConfirmation: null,
      alert: {}
    };
  },
  methods: {
    async submit(e) {
      e.preventDefault();
      this.alert = {};
      const isValid = await this.$validator.validate();
      if (isValid) {
        httpPost("/install", {
          email: this.email,
          realName: this.realName,
          password: this.password
        })
          .then(() => {
            this.$router.push({ name: "install" });
          })
          .catch(err => {
            this.alert = { ok: false, message: err };
          });
      }
    }
  }
};
</script>

// dashboard/src/pages/Install.tsx
import { Form, Input, message } from 'antd'
import { FormComponentProps } from 'antd/lib/form/Form'
import * as React from 'react'
import { FormattedMessage, InjectedIntlProps, injectIntl, intlShape } from 'react-intl'
import { RouteComponentProps, withRouter } from 'react-router'

import { formItemLayout } from '../components/form'
import Submit from '../components/form/Submit'
import { httpPost } from '../utils/request'
import Layout from './users/SharedLinks'

const FormItem = Form.Item

class Widget extends React.Component<RouteComponentProps<any> & InjectedIntlProps & FormComponentProps> {
  public static propTypes: React.ValidationMap<any> = {
    intl: intlShape.isRequired,
  }
  public comparePasswords = (_: any, value: string, callback: (m?: string) => void) => {
    const { form, intl } = this.props
    if (value && value !== form.getFieldValue('password')) {
      callback(intl.formatMessage({ id: "form.validations.password-confirmation" }))
    } else {
      callback()
    }
  }
  public handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const { form, history, intl } = this.props
    form.validateFields((err, values) => {
      if (!err) {
        httpPost("/install", values).then((_) => {
          message.success(intl.formatMessage({ id: "flashes.success" }))
          history.push("/users/sign-in")
        }).catch(message.error)
      }
    })
  }
  public render() {
    const { formatMessage } = this.props.intl
    const { getFieldDecorator } = this.props.form

    return (<Layout title="nut.install.title">
      <Form onSubmit={this.handleSubmit}>
        <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.email" />}>
          {
            getFieldDecorator('email', {
              rules: [
                {
                  message: formatMessage({ id: "form.validations.email" }),
                  required: true,
                  type: 'email',
                }
              ]
            })(<Input />)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.username" />}>
          {
            getFieldDecorator('realName', {
              rules: [
                {
                  max: 32,
                  message: formatMessage({ id: "form.validations.username" }),
                  min: 2,
                  required: true,
                }
              ]
            })(<Input />)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.password" />}>
          {
            getFieldDecorator('password', {
              rules: [
                {
                  max: 32,
                  message: formatMessage({ id: "form.validations.password" }),
                  min: 6,
                  required: true,
                }
              ]
            })(<Input type="password" />)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id="form.labels.password-confirmation" />}>
          {
            getFieldDecorator('passwordConfirmation', {
              rules: [
                {
                  message: formatMessage({ id: "form.validations.required" }),
                  required: true,
                },
                {
                  validator: this.comparePasswords,
                },
              ]
            })(<Input type="password" />)
          }
        </FormItem>
        <Submit />
      </Form>
    </Layout>)
  }
}


export default withRouter(injectIntl(Form.create()(Widget)))
