// dashboard/src/plugins/nut/users/Logs.vue
<template>
  <dashboard-layout v-bind:title="title">
    <v-data-table :headers="headers" :items="items" class="elevation-1">
      <template v-slot:items="props">
        <td>{{ props.item.createdAt|moment('llll') }}</td>
        <td>{{ props.item.ip }}</td>
        <td>{{ props.item.message }}</td>
      </template>
    </v-data-table>
  </dashboard-layout>
</template>

<script>
import { get as httpGet } from "@/request";

export default {
  name: "users-logs",
  data() {
    return {
      items: []
    };
  },
  created() {
    httpGet(`/users/logs?limit=${1 << 10}`).then(rst => {
      this.items = rst;
    });
  },
  computed: {
    headers() {
      return [
        {
          text: this.$i18n.t("form.labels.created-at"),
          value: "createdAt"
        },
        {
          text: this.$i18n.t("form.labels.ip"),
          value: "ip"
        },
        {
          text: this.$i18n.t("form.labels.message"),
          value: "message"
        }
      ];
    },
    title() {
      return this.$i18n.t("nut.users.logs.title");
    }
  }
};
</script>

// ant-design-pro/src/plugins/nut/users/Logs.tsx
import React, { Component } from "react";
import {
  injectIntl,
  FormattedMessage,
  WrappedComponentProps
} from "react-intl";
import { Row, Table, Col, message } from "antd";
import { ColumnProps } from "antd/es/table";

import Layout from "../../../layouts/dashboard";
import { show as moment } from "../../../utils/moment";
import { get as httpGet } from "../../../utils/request";

interface ILog {
  id: number;
  ip: string;
  message: string;
  createdAt: Date;
}

interface IProps {}
interface IState {
  items: ILog[];
  columns: ColumnProps<ILog>[];
}

class Widget extends Component<WrappedComponentProps & IProps, IState> {
  constructor(props: WrappedComponentProps & IProps) {
    super(props);
    this.state = {
      items: [],
      columns: [
        {
          title: <FormattedMessage id="attributes.created-at" />,
          render: (text: any, record: ILog) => moment(record.createdAt),
          width: 320,
          key: "createdAt"
        },
        {
          title: <FormattedMessage id="attributes.message" />,
          dataIndex: "message",
          key: "message"
        }
      ]
    };
  }
  componentDidMount() {
    httpGet("/users/logs?page=1&size=1024")
      .then(rst => {
        this.setState({ items: rst.items });
      })
      .catch(message.error);
  }
  public render() {
    const { intl } = this.props;
    const title = { id: "nut.logs.title" };
    return (
      <Layout title={intl.formatMessage(title)}>
        <Row>
          <Col
            sm={{
              span: 24
            }}
            md={{
              span: 12,
              offset: 1
            }}
          >
            <h1>
              <FormattedMessage {...title} />
            </h1>
          </Col>
          <Col
            sm={{
              span: 24
            }}
            md={{
              span: 22,
              offset: 1
            }}
          >
            <Table<ILog>
              rowKey="id"
              bordered={true}
              dataSource={this.state.items}
              columns={this.state.columns}
            />
          </Col>
        </Row>
      </Layout>
    );
  }
}

export default injectIntl(Widget);
