// dashboard/src/plugins/nut/users/SignIn.vue
<template>
  <application-layout
    v-bind:alert="alert"
    v-bind:onSubmit="submit"
    v-bind:title="this.$t('nut.users.sign-in.title')"
  >
    <v-form>
      <v-text-field
        prepend-icon="person"
        name="login"
        v-model="login"
        :error-messages="errors.collect('login')"
        v-validate="'required'"
        :label="this.$t('nut.users.sign-in.login')"
        type="text"
      />
      <v-text-field
        id="password"
        prepend-icon="lock"
        v-model="password"
        :error-messages="errors.collect('password')"
        v-validate="'required'"
        name="password"
        :label="this.$t('form.labels.password')"
        type="password"
      />
    </v-form>
  </application-layout>
</template>

<script>
import { post as httpPost } from "@/request";
import { set as setToken } from "@/token";
import { USERS_SIGN_IN } from "@/store";

export default {
  name: "users-sign-in",
  data() {
    return { login: null, password: null, alert: {} };
  },
  methods: {
    async submit(e) {
      e.preventDefault();
      this.alert = {};
      const isValid = await this.$validator.validate();
      if (isValid) {
        httpPost("/users/sign-in", {
          login: this.login,
          password: this.password
        })
          .then(res => {
            setToken(res.data);
            this.$store.commit(USERS_SIGN_IN, res.data);
            this.$router.push({ name: "home" });
          })
          .catch(err => {
            this.alert = { ok: false, message: err };
          });
      }
    }
  }
};
</script>

// ant-design-pro/src/plugins/nut/users/SignIn.tsx
import React, { Component } from "react";
import { connect } from "react-redux";
import { Button, Form, Input, message } from "antd";
import {
  injectIntl,
  WrappedComponentProps,
  FormattedMessage
} from "react-intl";
import { withRouter, RouteComponentProps } from "react-router";

import { post as httpPost } from "../../../utils/request";
import { signIn } from "../../../actions";
import Layout from "../../../layouts/application";
import { LAYOUT, TAIL_LAYOUT } from "../../../components/form";

const FormItem = Form.Item;

interface IProps {
  signIn: typeof signIn;
}

interface IState {}

class Widget extends Component<
  RouteComponentProps<any> & WrappedComponentProps & IProps,
  IState
> {
  onFinish = (values: any) => {
    const { intl, signIn, history } = this.props;
    httpPost("/users/sign-in", values)
      .then(rst => {
        signIn(rst.token);
        message.success(intl.formatMessage({ id: "flashes.success" }));
        history.push("/users/logs");
      })
      .catch(message.error);
  };
  public render() {
    const { formatMessage } = this.props.intl;
    const title = { id: "nut.users.sign-in.title" };
    return (
      <Layout title={formatMessage(title)}>
        <Form
          {...LAYOUT}
          name="nut.sign-in"
          initialValues={{}}
          onFinish={this.onFinish}
        >
          <FormItem
            name="login"
            rules={[
              {
                required: true
              }
            ]}
            label={<FormattedMessage id="attributes.login" />}
          >
            <Input />
          </FormItem>
          <FormItem
            name="password"
            rules={[
              {
                required: true
              }
            ]}
            label={<FormattedMessage id="attributes.password" />}
          >
            <Input type="password" />
          </FormItem>
          <FormItem {...TAIL_LAYOUT}>
            <Button type="primary" htmlType="submit">
              <FormattedMessage id="buttons.submit" />
            </Button>
          </FormItem>
        </Form>
      </Layout>
    );
  }
}

export default injectIntl(connect(() => ({}), { signIn })(withRouter(Widget)));
